### ISSUE TITLE
History with back button issue

### ISSUE THREAD

**Issue by vbeaulieu2** [Profiscience/ko-component-router#54]
The browser back button does not seem to be handled correctly. It pushes a "/" at the end of the url instead of bringing me back to the earlier level. 
for routes : 
 '/':'home',    '/RequestList': 'list',    '/Request/:id': 'request'
navigation goes : 
 http://localhost:9999/  
use link with  data-bind="path: '/RequestList'"  navigates to : 
http://localhost:9999/RequestList
back button navigates to: 
http://localhost:56830/RequestList/
notice the "/" added at the end instead of returning to  http://localhost:9999/  

the back button is more broken with more levels.

**Comment by caseyWebb** [comment]
@vbeaulieu2 What browser is this in? I'm not able to repro in Chrome, Safari, or Firefox.

[This is the code I'm using](https://gist.github.com/caseyWebb/9df8fc9e92be23814e661aefaba4b3a8)

**Comment by vbeaulieu2** [comment]
Chrome and IE 11
Go to your docs page, nested routing, use foo-ception 3 times and play with back and forward.
You should see a similar problem in the url. At some point back and forward don't seem to work anymore.

**Comment by caseyWebb** [comment]
I was able to reproduce a bit of unexpected behavior, but nothing like you've described. Could you check out the docs again and see if the problem you were having persists? If so, you could list the steps to repro?

Thanks

**Comment by vbeaulieu2** [comment]
My first description comes from a project a bit more complex so I am not able to give you a simple version of the problem yet. I noticed later that the foo-ception exemple had a similar behavior and I think both are related.

I have recorded a quick video of the problem on your docs page and attached it here.
The result is that both history buttons and adress bar becomes invalid at some point.
[Recording #8.zip](https://github.com/Profiscience/ko-component-router/files/311825/Recording.8.zip)

I will try send you some code later this week if you need another version of the problem.

**Comment by caseyWebb** [comment]
The behavior you've recorded is due to the fact that the example is using recursive routing; I can't imagine this being a real-word scenario, but I've fixed it nonetheless for demo purposes.

**Comment by vbeaulieu2** [comment]
Didn't fix the problem in my app.
I'll get back to you with a simple version of the problem as soon as i can.

Thanks

**Comment by vbeaulieu2** [comment]
I came up with this example

Hope it helps. Thanks again.

Steps to reproduce : .
1. starting adress should be http://localhost.../main
2. use "request list" link. adress is now http://localhost.../main/request
3. use back button. final adress: http://localhost.../main/request/main/

components and routes : 

```

 ko.components.register('app', {
    viewModel: function app() {
      function app(name) {
        this.routes = {
          '/': '',
          '/request': 'requestList'
        }
      };
      return app
    },
    template: '<a data-bind="path: \'/request\'">Request list</a><br /><br /><ko-component-router params="routes: routes, hashbang: false, persistQuery: true, base: \'/main\'"></ko-component-router>' 
  });

  ko.components.register('requestList', {
    viewModel: function requestListViewModel() {
      var self = this;
      this.routes = {
        '/': '',
        '/:id': 'request',
        '/edit/:id': 'editRequest',
      };
    },
    template: ('<div>' +
              '  Request List' +
              '  <br />' +
              '  <a data-bind="path: \'/8\'">Go To Request with ID : 8</a><br />' +
              '  <a data-bind="path: \'/12\'">Go To Request with ID : 12</a><br />' +
              '  Router content' +
              '  <ko-component-router params="routes: routes">' +
              '  </ko-component-router>' +
              '</div>')
  });

  ko.components.register('request', {
    viewModel: function requestViewModel(ctx) {
      var self = this;
      this.id = ko.observable(ctx.params.id ? ctx.params.id() : null);
    },
    template: '<div>' +
                '<h1>Request Header</h1>' +
                '<div>' +
                 ' ID: <span data-bind="text: id"></span>   <br />' +
                 ' <a data-bind="path: \'/edit/\'+$router.params.id() ">View</a>' +
                '</div>' +
              '</div>'
  });

  ko.components.register('editRequest', {
    template: 'edit...'
  });
```

**Comment by caseyWebb** [comment]
Should be closed via f1a7017e4248b04fb17c8983a13269f0673cacfa
